# Generated by Django 6.0.4 on 2026-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_original', models.ImageField(blank=True, null=True, upload_to='brands/original/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='brands/medium/')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='brands/thumbnail/')),
                ('is_processed', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
