# Generated by Django 6.0.4 on 2026-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_on_shop',
            field=models.BooleanField(default=True),
        ),
    ]
