# Generated by Django 6.0.4 on 2026-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='None', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
