# Generated by Django 6.0.4 on 2026-04-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='specifications',
            old_name='Product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='nill', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='specifications',
            name='spec',
            field=models.CharField(default='NILL', max_length=200),
        ),
    ]
