# Generated by Django 6.0.4 on 2026-04-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_warranty'),
        ('product', '0002_enable_trigram'),
    ]

    operations = [
    ]
