# Generated by Django 6.0.4 on 2026-08-15 15:39

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_strings_forward(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    Category = apps.get_model('product', 'Category')
    ProductCategory = apps.get_model('product', 'ProductCategory')

    category_cache = {}

    for product in Product.objects.exclude(category__isnull=True).exclude(category=""):
        name = product.category.strip()

        if not name or name.lower() == "nill":
            continue

        category = category_cache.get(name.lower())

        if category is None:
            category, _ = Category.objects.get_or_create(
                name__iexact=name,
                defaults={"name": name},
            )
            category_cache[name.lower()] = category

        ProductCategory.objects.get_or_create(product=product, category=category)


def migrate_category_strings_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_enable_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductCategory', to='product.category'),
        ),
        migrations.RunPython(
            migrate_category_strings_forward,
            migrate_category_strings_backward,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
