# Generated by Django 6.0.4 on 2026-06-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_0002_alter_product_warranty_0002_enable_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagevariant',
            name='jpg_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants_jpg/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='No Warranty', max_length=100),
        ),
    ]
