# Generated by Django 6.0.4 on 2026-04-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='sectionproduct',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.homesection'),
        ),
    ]
