# Generated by Django 6.0.4 on 2026-04-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
