# Generated by Django 6.0.4 on 2026-04-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homesection_is_active'),
        ('homepage', '0002_initial'),
    ]

    operations = [
    ]
